version: '2'
services:
  elasticsearch:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfiles/elastic_search/Dockerfile
  bot:
    env_file: .env
    build:
        context: .
        dockerfile: ./Dockerfiles/bot/Dockerfile
    command: python bot.py vectors
    volumes:
      - .:/bot
    depends_on:
        - elasticsearch
